apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mkf96fj83-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mkf96fj83-dotnet-basic 
  name: mkf96fj83-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mkf96fj83-dotnet-basic 
